# -*- coding: utf-8 -*-
"""troco.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XUSDuCnS5NKm6qmCfAWwh1-8JIKe7Mf1
"""

#troco

precoUnitario = float (input('Preço Unitário produto R$:_'))
quantidade =  float (input ('Quantidade Compra [_'))
total   = precoUnitario * quantidade 
pagamento = float (input ('Dinheiro R$ '))
troco = pagamento -total

print('Troco  R$ {}'.format(troco))